# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170718_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='startingdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
